CREATE SEQUENCE id_produto;
CREATE SEQUENCE id_estoque;
CREATE SEQUENCE id_cardapio;
CREATE SEQUENCE id_cardapio_tempo_preparo;
CREATE SEQUENCE id_ingrediente_cardapio;
CREATE SEQUENCE id_funcionario;
CREATE SEQUENCE id_pessoa;
CREATE SEQUENCE id_endereco;
CREATE SEQUENCE id_usuario;

CREATE TABLE tb_produto (id_produto BIGINT NOT NULL DEFAULT nextval('id_produto'), descricao VARCHAR(255) UNIQUE, tipo VARCHAR(255), PRIMARY KEY (id_produto));
CREATE TABLE tb_estoque (id_estoque BIGINT NOT NULL DEFAULT nextval('id_estoque'), medida VARCHAR(255), medida_reposicao VARCHAR(255), preco FLOAT, quantidade_reposicao INTEGER, quantidade INTEGER, id_produto BIGINT, PRIMARY KEY (id_estoque));
CREATE TABLE tb_cardapio (id_cardapio BIGINT NOT NULL DEFAULT nextval('id_cardapio'), categoria VARCHAR(255), descricao VARCHAR(255) UNIQUE, preco FLOAT, situacao VARCHAR(255), id_cardapio_tempo_preparo BIGINT, PRIMARY KEY (id_cardapio));
CREATE TABLE tb_cardapio_tempo_preparo (id_cardapio_tempo_preparo BIGINT NOT NULL DEFAULT nextval('id_cardapio_tempo_preparo'), hora INTEGER, minuto INTEGER, segundo INTEGER, id_cardapio BIGINT, PRIMARY KEY (id_cardapio_tempo_preparo));
CREATE TABLE tb_ingrediente_cardapio (id_ingrediente_cardapio BIGINT NOT NULL DEFAULT nextval('id_ingrediente_cardapio'), medida VARCHAR(255), quantidade INTEGER, id_cardapio BIGINT, id_estoque BIGINT, PRIMARY KEY (id_ingrediente_cardapio));
CREATE TABLE tb_funcionario (id_funcionario BIGINT NOT NULL DEFAULT nextval('id_funcionario'), cargo VARCHAR(255), celular VARCHAR(255), data_admissao TIMESTAMP, data_desligamento TIMESTAMP, motivo_desligamento VARCHAR(255), salario FLOAT, situacao VARCHAR(255), telefone_fixo VARCHAR(255), id_usuario BIGINT, id_pessoa BIGINT, PRIMARY KEY (id_funcionario));
CREATE TABLE tb_pessoa (id_pessoa BIGINT NOT NULL DEFAULT nextval('id_pessoa'), cpf VARCHAR(255), data_nascimento DATE, nome VARCHAR(255), sexo VARCHAR(255), id_endereco BIGINT, PRIMARY KEY (id_pessoa));
CREATE TABLE tb_endereco (id_endereco BIGINT NOT NULL DEFAULT nextval('id_endereco'), bairro VARCHAR(255), cep VARCHAR(255), cidade VARCHAR(255), complemento VARCHAR(255), conjunto VARCHAR(255), estado VARCHAR(255), numero VARCHAR(255), rua VARCHAR(255), PRIMARY KEY (id_endereco));
CREATE TABLE tb_usuario (id_usuario BIGINT NOT NULL DEFAULT nextval('id_usuario'), senha VARCHAR(60) NOT NULL, situacao VARCHAR(255), usario VARCHAR(45) NOT NULL UNIQUE, PRIMARY KEY (id_usuario));
CREATE TABLE tb_usuario_role (id_usuario BIGINT, role VARCHAR(255) NOT NULL);
ALTER TABLE tb_estoque ADD CONSTRAINT tbestoqueidproduto FOREIGN KEY (id_produto) REFERENCES tb_produto (id_produto);
ALTER TABLE tb_cardapio ADD CONSTRAINT tbcrdpdcrdptmpprpr FOREIGN KEY (id_cardapio_tempo_preparo) REFERENCES tb_cardapio_tempo_preparo (id_cardapio_tempo_preparo);
ALTER TABLE tb_cardapio_tempo_preparo ADD CONSTRAINT tbcrdptmpprprdcrdp FOREIGN KEY (id_cardapio) REFERENCES tb_cardapio (id_cardapio);
ALTER TABLE tb_ingrediente_cardapio ADD CONSTRAINT tbngrdntcrdpiodstq FOREIGN KEY (id_estoque) REFERENCES tb_estoque (id_estoque);
ALTER TABLE tb_ingrediente_cardapio ADD CONSTRAINT tbngrdntcrdpodcrdp FOREIGN KEY (id_cardapio) REFERENCES tb_cardapio (id_cardapio);
ALTER TABLE tb_funcionario ADD CONSTRAINT tbfncionariodsario FOREIGN KEY (id_usuario) REFERENCES tb_usuario (id_usuario);
ALTER TABLE tb_funcionario ADD CONSTRAINT tbfncionariodpssoa FOREIGN KEY (id_pessoa) REFERENCES tb_pessoa (id_pessoa);
ALTER TABLE tb_pessoa ADD CONSTRAINT tbpessoaidendereco FOREIGN KEY (id_endereco) REFERENCES tb_endereco (id_endereco);
ALTER TABLE tb_usuario_role ADD CONSTRAINT tbsarioroledsuario FOREIGN KEY (id_usuario) REFERENCES tb_usuario (id_usuario);